export const navLinks = [
    {
        id:1,
        url:"#home",
        label:"Home",
    },
    {
        id:2,
        url:"#about",
        label:"About",
    },
    {
        id:3,
        url:"#services",
        label:"Services",
    },
    {
        id:4,
        url:"#projects",
        label:"Projects",
    },
    {
        id:5,
        url:"#skills",
        label:"Skills",
    },
    {
        id:6,
        url:"#contacts",
        label:"Contacts",
    },
  
]